#配置文件环境配置
spring:
  profiles:
    active: dev

#端口
server: 
  port: 8888
    
---
spring:
  profiles: dev
  datasource:
        name: test
        url: jdbc:mysql://localhost:3306/wenrc?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false&amp;zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        removeAbandonedTimeout: 180
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  #jpa:
      #properties:
            #hibernate:
                  #show_sql: true
                  #format_sql: true
mybatis:
  type-aliases-package: com.wenrc.reward.domain
  #mapper-locations: classpath:mappings/**/*.xml
  mapper-locations: classpath*:com/wenrc/reward/mapper/*.xml 
  #configuration:
        #map-underscore-to-camel-case: true
        #default-fetch-size: 100
        #default-statement-timeout: 30
logging:
  level:
        com.wenrc.reward: DEBUG
server:
  port: 8080
  
---
spring:
  profiles: prod
server:
  port: 8082
  
---
spring:
  profiles: test
server:
  port: 8081
